name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - mlflow=2.4.1
  - pyyaml=5.3.1
  - hydra-core=1.3.2
  - numpy=1.19.0
  - pip=20.3.3
  - pip:
      - wandb==0.10.31