name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=20.3.3
  - mlflow=2.4.1
  - hydra-core=1.3.2
  - requests==2.31.0
  - git=2.30.2
  - cookiecutter=1.7.2
  - pip:
      - ipython==7.21.0
      - notebook==6.2.0
      - jupyterlab==3.0.10
      - cookiecutter==1.7.2
      - matplotlib==3.3.4
      - pandas==1.2.3
      - wandb==0.10.3
      - hydra-joblib-launcher==1.1.2


